spring:
  application:
    name: Spring Boot Demo Application

  datasource:
    url: jdbc:postgresql://localhost:5432/finalProject
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true